server:
  port: 8760
  
#在多网卡环境下，优先使用preferred-networks配置的ip注册到注册中心（支持正则表达式过滤）
spring:
  cloud:
    inetutils:
      preferred-networks: 192.168.14.
      
#配置注册中心地址，设置ip优先，也可以使用hostname
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/